[package]
name = "bee-type-id-derive"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Derive macros for the bee-type-id crate"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "type" ]
homepage = "https://www.iota.org"

[lib]
proc-macro = true

[dependencies]
blake3 = "0.3"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[dev-dependencies]
bee-type-id = { path = "../bee-type-id" }
