[package]
name = "bee-api-types"
version = "1.0.0-beta.1"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "Common types required by nodes and clients APIs like bodies, errors, responses and DTOs."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "bee", "framework", "node", "api" ]
homepage = "https://www.iota.org"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
bee-block = { version = "1.0.0-beta.2", path = "../../bee-block", default-features = false, features = [ "dto" ] }
bee-ledger-types = { version = "1.0.0-beta.2", path = "../../bee-ledger/bee-ledger-types", default-features = false }
bee-protocol-types = { version = "1.0.0-beta.1", path = "../../bee-protocol/bee-protocol-types", default-features = false, optional = true }

axum = { version = "0.5.4", default-features = false, features = [ "json" ] }
serde = { version = "1.0.137", default-features = false, features = [ "derive" ] }
thiserror = { version = "1.0.31", default-features = false }

[features]
default = [ "peer" ]
peer = [ "bee-protocol-types" ]
