[package]
name = "bee-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
bee-runtime = { version = "0.1.1-alpha", path = "../../../bee-runtime", default-features = false }

async-trait = { version = "0.1.51", default-features = false }
