[package]
name = "bee-logger"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "A logger backend for the `log` crate."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "logger" ]
homepage = "https://www.iota.org"

[dependencies]
chrono = { version = "0.4", default-features = false, features = [ "clock" ] }
fern = { version = "0.6", default-features = false, features = [ "colored" ] }
log = { version = "0.4", default-features = false, features = [ "serde" ] }
serde = { version = "1.0", default-features = false, features = [ "derive", "std" ], optional = true }
thiserror = { version = "1.0", default-features = false }
