[package]
name = "bee-logger"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "A logger backend for the `log` crate"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "logger" ]
homepage = "https://www.iota.org"

[dependencies]
chrono = "0.4"
fern = { version = "0.6", features = [ "colored" ] }
log = { version = "0.4", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ], optional = true }
thiserror = "1.0"
