[package]
name = "bee-gossip"
version = "0.6.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "Allows peers in the same IOTA network to exchange gossip messages with each other."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "bee", "framework", "network", "gossip" ]
homepage = "https://www.iota.org"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[package.metadata.cargo-udeps.ignore]
development = [ "fern", "hex", "serial_test" ]

[features]
default = [ ]
full = [
  "async-trait",
  "bee-runtime",
  "futures",
  "libp2p/dns-tokio",
  "libp2p/identify",
  "libp2p/mplex",
  "libp2p/noise",
  "libp2p/tcp-tokio",
  "libp2p/yamux",
  "log",
  "once_cell",
  "rand",
  "serde",
  "thiserror",
  "tokio",
  "tokio-stream",
]

[dependencies]
bee-runtime = { version = "0.1.1-alpha", path = "../../bee-runtime", default-features = false, optional = true }

async-trait = { version = "0.1.56", default-features = false, optional = true }
futures = { version = "0.3.21", default-features = false, optional = true }
hashbrown = { version = "0.12.1", default-features = false, features = [ "ahash", "inline-more" ] }
libp2p = { version = "0.46.1", default-features = false, optional = true }
libp2p-core = { version = "0.34.0", default-features = false }
log = { version = "0.4.17", default-features = false, optional = true }
once_cell = { version = "1.12.0", default-features = false, optional = true }
rand = { version = "0.8.5", default-features = false, optional = true }
serde = { version = "1.0.137", default-features = false, features = [ "derive" ], optional = true }
thiserror = { version = "1.0.31", default-features = false, optional = true }
tokio = { version = "1.19.2", default-features = false, features = [ "macros", "rt", "time" ], optional = true }
tokio-stream = { version = "0.1.9", default-features = false, features = [ "time" ], optional = true }

[dev-dependencies]
fern = { version = "0.6.1", default-features = false }
hex = { version = "0.4.3", default-features = false, features = [ "alloc" ] }
serial_test = { version = "0.7.0", default-features = false }
tokio = { version = "1.19.2", default-features = false, features = [ "io-std", "io-util", "macros", "rt", "rt-multi-thread", "signal", "time" ] }

[[example]]
name = "chat"
required-features = [ "full" ]
