[package]
name = "bee-storage-sled"
version = "0.4.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "A bee-storage implementation for the Sled backend"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "sled" ]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { version = "0.5.0", path = "../../bee-common/bee-common", default-features = false }
bee-ledger = { version = "0.6.0", path = "../../bee-ledger", default-features = false }
bee-message = { version = "0.2.0", path = "../../bee-message", default-features = false }
bee-storage = { version = "0.9.0", path = "../bee-storage", default-features = false }
bee-tangle = { version = "0.2.0", path = "../../bee-tangle", default-features = false }

num_cpus = { version = "1.13.0", default-features = false }
serde = { version = "1.0.130", default-features = false, features = [ "derive" ] }
sled = { version = "0.34.7", default-features = false, features = [ "compression" ]}
thiserror = "1.0.30"

[dev-dependencies]
bee-storage-test = { path = "../bee-storage-test", default-features = false }
bee-test = { path = "../../bee-test", default-features = false }
