[package]
name = "bee-storage-sled"
version = "0.4.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "A bee-storage implementation for the Sled backend."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "sled" ]
homepage = "https://www.iota.org"

[dependencies]
bee-message = { path = "../../bee-message", default-features = false, features = [ "metadata" ] }
bee-storage = { path = "../bee-storage", default-features = false }

packable = { version = "0.1.0", default-features = false, features = [ "io" ] }
serde = { version = "1.0.130", default-features = false, features = [ "derive" ] }
sled = { version = "0.34.7", default-features = false, features = [ "compression" ]}
thiserror = "1.0.30"

[dev-dependencies]
bee-storage-test = { path = "../bee-storage-test", default-features = false }
