[package]
name = "bee-storage-sled"
version = "0.4.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "A bee-storage implementation for the Sled backend"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "sled" ]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { version = "0.5.0", path = "../../bee-common/bee-common" }
bee-ledger = { version = "0.5.0", path = "../../bee-ledger" }
bee-message = { version = "0.1.5", path = "../../bee-message" }
bee-storage = { version = "0.9.0", path = "../bee-storage" }
bee-tangle = { version = "0.2.0", path = "../../bee-tangle" }

num_cpus = "1.13.0"
serde = { version = "1.0.130", features = [ "derive" ] }
sled = { version = "0.34.7", features = [ "compression" ]}
thiserror = "1.0.30"

[dev-dependencies]
bee-storage-test = { path = "../bee-storage-test" }
bee-test = { path = "../../bee-test" }
