[package]
name = "bee-storage-sled"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "A bee-storage implementation for the Sled backend"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "sled"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { version = "0.4.1", path = "../../bee-common/bee-common" }
bee-ledger = { version = "0.4.0", path = "../../bee-ledger" }
bee-message = { version = "0.1.3", path = "../../bee-message" }
bee-storage = { version = "0.6.0", path = "../bee-storage" }
bee-tangle = { version = "0.1.0", path = "../../bee-tangle" }

async-trait = "0.1"
futures = "0.3"
num_cpus = "1.13"
pin-project = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
sled = { version = "0.34.6", features = [ "compression" ]}
thiserror = "1.0"

[dev-dependencies]
bee-storage-test = { path = "../bee-storage-test" }
bee-test = { path = "../../bee-test" }

tokio = { version = "1.6", features = [ "macros", "rt" ] }
