[package]
name = "bee-storage-sled"
version = "0.7.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "A bee-storage implementation for the Sled backend"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "sled" ]
homepage = "https://www.iota.org"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
bee-block = { version = "1.0.0-beta.6", path = "../../bee-block", default-features = false }
bee-ledger = { version = "0.7.0", path = "../../bee-ledger/bee-ledger", default-features = false }
bee-storage = { version = "1.0.0-beta.1", path = "../bee-storage", default-features = false }
bee-tangle = { version = "0.3.0", path = "../../bee-tangle", default-features = false }

num_cpus = { version = "1.13.1", default-features = false }
packable = { version = "0.5.0", default-features = false, features = [ "serde" ] }
serde = { version = "1.0.143", default-features = false, features = [ "derive" ] }
sled = { version = "0.34.7", default-features = false, features = [ "compression" ]}
thiserror = { version = "1.0.32", default-features = false }

[dev-dependencies]
bee-storage-test = { path = "../bee-storage-test", default-features = false }
