// Copyright 2021 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

mod flamegraph;
mod log;

pub use self::{flamegraph::FlamegraphLayer, log::LogLayer};

use crate::{util::Flamegrapher, Error};

use bee_common::logger::LoggerConfig;

use tracing::Metadata;
use tracing_subscriber::{
    filter::{FilterFn, Filtered},
    registry::Registry,
    Layer,
};

use std::path::Path;

/// The flamegraph layer type.
pub type FlamegraphFilteredLayer = Filtered<FlamegraphLayer, FilterFn, Registry>;

/// Creates a new [`FlamegraphFilteredLayer`].
///
/// The given path describes the desired output location of the folded stack file that is generated by
/// this layer during runtime. This file can then be used to produce a flamegraph by a [`Flamegrapher`]
/// instance, or by the [`inferno`] tool.
///
/// Returns a `Result` of the tuple containing the [`FlamegraphFilteredLayer`] and a [`Flamegrapher`] that
/// can be used to produce the flamegraph image at the end of profiling. This can be ignored if you just
/// need the folded stack file, or will use [`inferno`] externally for the graph generation.
///
/// # Errors
/// This function can fail in the following ways:
///  - There was an error creating/truncating the folded stack file at the given location.
///
/// # Panics
/// This function will panic if the program is not built with `--cfg tokio_unstable`.
pub fn flamegraph_layer<P: AsRef<Path>>(stack_filename: P) -> Result<(FlamegraphFilteredLayer, Flamegrapher), Error> {
    #![allow(clippy::assertions_on_constants)]
    assert!(
        cfg!(tokio_unstable),
        "task tracing requires building with RUSTFLAGS=\"--cfg tokio_unstable\"!"
    );

    fn filter_fn(meta: &Metadata<'_>) -> bool {
        if meta.is_event() {
            return false;
        }

        meta.target().starts_with("runtime") || meta.target().starts_with("tokio") || meta.target() == "bee::observe"
    }

    let filter = FilterFn::new(filter_fn as for<'r, 's> fn(&'r tracing::Metadata<'s>) -> bool);
    let (layer, flamegrapher) = FlamegraphLayer::new(stack_filename)
        .map(|(layer, _flamegrapher)| (layer.with_filter(filter), _flamegrapher))?;

    Ok((layer, flamegrapher))
}

/// Creates a new [`LogLayer`](layer::LogLayer), using the parameters provided by the given [`LoggerConfig`].
///
/// This should allow the subscriber to perform logging in an identical fashion to the functionality provided
/// in [`bee_common`].
///
/// # Errors
/// This function can fail in the following ways:
///  - An [`io::Error`](std::io::Error) was encountered when creating any log files required by the config.
pub fn log_layer(config: LoggerConfig) -> Result<LogLayer, Error> {
    LogLayer::new(config)
}
