[package]
name = "bee-network-packet"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Processing of network packets."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "network packets" ]
homepage = "https://www.iota.org"

[dependencies]
base64 = { version = "0.13", default-features = false, features = [ "std" ] }
bs58 = { version = "0.4", default-features = false, features = [ "alloc" ] }
iota-crypto = { version = "0.7.0", default-features = false, features = [ "ed25519", "random", "sha" ] }
num = { version = "0.4", default-features = false }
num-derive = { version = "0.3", default-features = false }
num-traits = { version = "0.2", default-features = false }
prost = { version = "0.8", default-features = false }

[build-dependencies]
prost-build = { version = "0.8", default-features = false }
