[package]
name = "bee-common-derive"
version = "0.1.1-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Derive macros for the bee-common crate"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "common"]
homepage = "https://www.iota.org"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
