[package]
name = "bee-protocol"
version = "0.2.2"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "All workers enabling the IOTA protocol."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "protocol" ]
homepage = "https://www.iota.org"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
bee-autopeering = { version = "0.5.0", path = "../../bee-network/bee-autopeering", default-features = false }
bee-block = { version = "1.0.0-beta.1", path = "../../bee-block", default-features = false, features = [ "serde" ] }
bee-gossip = { version = "0.6.0", path = "../../bee-network/bee-gossip", default-features = false, features = [ "full" ] }
bee-ledger = { version = "0.7.0", path = "../../bee-ledger/bee-ledger", default-features = false }
bee-pow = { version = "1.0.0-alpha.1", default-features = false }
bee-protocol-types = { version = "1.0.0-alpha.1", path = "../bee-protocol-types", default-features = false }
bee-runtime = { version = "0.1.1-alpha", path = "../../bee-runtime", default-features = false }
bee-storage = { version = "0.12.0", path = "../../bee-storage/bee-storage", default-features = false }
bee-tangle = { version = "0.3.0", path = "../../bee-tangle", default-features = false }

async-channel = { version = "1.6.1", default-features = false }
async-priority-queue = { version = "0.1.1", default-features = false }
async-trait = { version = "0.1.56", default-features = false }
futures = { version = "0.3.21", default-features = false }
futures-util = { version = "0.3.21", default-features = false }
fxhash = { version = "0.2.1", default-features = false }
hex = { version = "0.4.3", default-features = false }
log = { version = "0.4.17", default-features = false }
num_cpus = { version = "1.13.1", default-features = false }
packable = { git = "https://github.com/pvdrz/common-rs", rev = "60f4b8b2109362e2c2e7f94d0034a96d21aa2c45", default-features = false }
parking_lot = { version = "0.12.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
ref-cast = { version = "1.0.7", default-features = false }
serde = { version = "1.0.137", default-features = false, features = [ "derive" ]}
thiserror = { version = "1.0.31", default-features = false }
tokio = { version = "1.19.2", default-features = false, features = [ "rt-multi-thread" ] }
tokio-stream = { version = "0.1.9", default-features = false }
twox-hash = { version = "1.6.3", default-features = false }

[dev-dependencies]
tokio = { version = "1.18.2", default-features = false, features = [ "macros" ] }
