[package]
name = "bee-task"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Task related utilities"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "task" ]
homepage = "https://www.iota.org"

[dependencies]
futures = { version = "0.3", default-features = false }
tokio = { version = "1.12", default-features = false, features = [ "rt" ] }
tracing = { version = "0.1", default-features = false, optional = true }

[features]
tokio-console = [ "tracing" ]
