[package]
name = "bee-packet"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Processing of network packets."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "network" ]
homepage = "https://www.iota.org"

[dependencies]
bee-identity = { path = "../bee-identity" }
bee-task = { path = "../../bee-common/bee-task" }
bee-peering-auto = { path = "../bee-peering-auto" }
bee-peering-manual = { path = "../bee-peering-manual" }

async-trait = { version = "0.1", default-features = false }
backstage = { git = "https://github.com/iotaledger/backstage", default-features = false, branch = "stable", optional = true }
base64 = { version = "0.13", default-features = false, features = [ "std" ] }
bs58 = { version = "0.4", default-features = false, features = [ "alloc" ] }
bytes = { version = "1.0", default-features = false }
iota-crypto = { version = "0.7.0", default-features = false, features = [ "ed25519", "random", "sha" ] }
log = { version = "0.4", default-features = false }
num = { version = "0.4", default-features = false }
num-derive = { version = "0.3", default-features = false }
num-traits = { version = "0.2", default-features = false }
prost = { version = "0.8", default-features = false }
prost-build = { version = "0.8", default-features = false }
serde = "1.0.130"
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1.5", default-features = false, features = [ "sync", "time", "rt", "io-util" ] }

[dev-dependencies]
anyhow = { version = "1.0", default-features = false }
env_logger = { version = "0.9", default-features = false }
tokio = { version = "1.5", default-features = false, features = [ "macros", "rt-multi-thread", "signal" ] }

[build-dependencies]
prost-build = { version = "0.8", default-features = false }
