[package]
name = "bee-ledger"
version = "0.7.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "All features required to compute and maintain the ledger state."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "ledger" ]
homepage = "https://www.iota.org"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = [ "--cfg", "doc_cfg" ]

[dependencies]
bee-block = { version = "1.0.0-beta.6", path = "../../bee-block", default-features = false, features = [ "std" ] }
bee-ledger-types = { version = "1.0.0-beta.2", path = "../bee-ledger-types", default-features = false }
bee-runtime = { version = "1.0.0-beta.1", path = "../../bee-runtime", default-features = false }
bee-storage = { version = "1.0.0-beta.1", path = "../../bee-storage/bee-storage", default-features = false }
bee-tangle = { version = "0.3.0", path = "../../bee-tangle", default-features = false }

async-trait = { version = "0.1.57", default-features = false }
bytes = { version = "1.1.0", default-features = false }
futures = { version = "0.3.21", default-features = false }
hashbrown = { version = "0.12.1", default-features = false }
iota-crypto = { version = "0.13.0", default-features = false, features = [ "blake2b" ] }
log = { version = "0.4.17", default-features = false }
packable = { version = "0.5.0", default-features = false, features = [ "serde", "io" ] }
prefix-hex = { version = "0.4.0", default-features = false }
ref-cast = { version = "1.0.9", default-features = false }
reqwest = { version = "0.11.11", default-features = false, features = [ "default-tls", "stream" ] }
serde = { version = "1.0.143", default-features = false, features = [ "derive" ] }
thiserror = { version = "1.0.32", default-features = false }
time-helper = { version = "0.1.0", default-features = false }
tokio = { version = "1.20.1", default-features = false, features = [ "sync", "fs" ] }
tokio-stream = { version = "0.1.9", default-features = false }
url = { version = "2.2.2", default-features = false, features = [ "serde" ] }
