[package]
name = "bee-common"
version = "1.0.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"

[features]
alloc = []

[dev-dependencies]
bee-common= { path = ".", features = ["alloc"] }

[build-dependencies]
autocfg = "1.0"

[dependencies]
