[package]
name = "bee-gossip2"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "Allows peers in the same IOTA network to exchange gossip messages with each other."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "bee", "framework", "network", "gossip" ]
homepage = "https://www.iota.org"

[dependencies]
libp2p = { version = "0.39.1", default-features = false, optional = true }
libp2p-core = { version = "0.29.0", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = [ "macros", "rt", "time" ], optional = true }
tokio-stream = { version = "0.1.7", default-features = false, features = [ "time" ], optional = true }
