[package]
name = "bee-inx"
version = "1.0.0-beta.1"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "Rust bindings for IOTA node extensions (INX)"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "plugin", "node", "inx", "bee" ]
homepage = "https://www.iota.org"

[dependencies]
bee-block = { version = "1.0.0-beta.3", path = "../bee-block", default-features = false, features = [ "inx", "std" ] }

futures = { version = "0.3.21", default-features = false }
inx = { version = "1.0.0-beta.2", default-features = false }
thiserror = { version = "1.0.31", default-features = false }
packable = { git = "https://github.com/pvdrz/common-rs", rev = "60f4b8b2109362e2c2e7f94d0034a96d21aa2c45", default-features = false }

[dev-dependencies]
tokio = { version = "1.18", default-features = false, features = [ "macros", "rt-multi-thread" ] }
futures = { version = "0.3", default-features = false }
