[package]
name = "bee-peering-manual"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Utilities to manually configure peers."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "manual peering" ]
homepage = "https://www.iota.org"

[dependencies]
bee-identity = { path = "../bee-identity" }

serde = "1.0.130"

[dev-dependencies]

[build-dependencies]
prost-build = { version = "0.8", default-features = false }
