[package]
name = "bee-time"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Time related utilities."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "time" ]
homepage = "https://www.iota.org"

[dependencies]
time = { version = "0.3.0", default-features = false, features = [ "formatting" ] }
