[package]
name = "bee-packable-derive"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Derive macros for the bee-packable crate"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "packable" ]
homepage = "https://www.iota.org"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/lib.rs"

[package.metadata.cargo-udeps.ignore]
development = [ "bee-packable" ]

[dependencies]
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "full", "extra-traits" ] }

[dev-dependencies]
bee-packable = { path = "../bee-packable" }

rustversion = { version = "1.0" }
trybuild = { version = "1.0", features = [ "diff" ] }
