[package]
name = "bee-plugin-version-checker"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "Version checker plugin for the Bee node."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "plugin", "version" ]
homepage = "https://www.iota.org"

[dependencies]
bee-runtime = { version = "0.1.1-alpha", path = "../../../bee-runtime", default-features = false }

async-trait = { version = "0.1.56", default-features = false }
futures = { version = "0.3.21", default-features = false }
log = { version = "0.4.17", default-features = false }
tokio = { version = "1.19.2", default-features = false, features = [ "signal", "rt", "macros", "rt-multi-thread" ] }
tokio-stream = { version = "0.1.9", default-features = false }
