[package]
name = "bee-plugin-mps"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2021"
description = "MPS plugin for the Bee node."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "plugin", "mps" ]
homepage = "https://www.iota.org"

[dependencies]
bee-plugin = { version = "0.1.0", path = "../bee-plugin", default-features = false }
bee-protocol = { version = "0.2.0", path = "../../../bee-protocol/bee-protocol", default-features = false }
bee-runtime = { version = "1.0.0-beta.1", path = "../../../bee-runtime", default-features = false }

async-trait = { version = "0.1.56", default-features = false }
log = { version = "0.4.17", default-features = false }
