# Duplicate this file to config.toml to use it

alias      = "bee"
bech32_hrp = "atoi"
network_id = "comnet1"

[logger]
[[logger.outputs]]
name              = "stdout"
level_filter      = "info"
target_filters    = []
target_exclusions = []
color_enabled     = true
[[logger.outputs]]
name              = "warn.log"
level_filter      = "warn"
target_filters    = []
target_exclusions = []

[network]
bind_address            = "/ip4/0.0.0.0/tcp/15600"
reconnect_interval_secs = 30
max_unknown_peers       = 4
max_discovered_peers    = 8

[network.peering]
#[[network.peering.peers]]
#address  = ""
#alias    = ""

[autopeering]
enabled                       = false
bind_address                  = "0.0.0.0:14626"
entry_nodes                   = [
    "/dns/entry.comnet.tanglebay.com/udp/14636/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC",
]
entry_nodes_prefer_ipv6       = false
run_as_entry_node             = false
drop_neighbors_on_salt_update = false
peer_storage_path             = "./storage/comnet/peers"

[protocol]
minimum_pow_score = 2000
[protocol.coordinator]
public_key_count  = 2
[[protocol.coordinator.public_key_ranges]]
public_key  = "2b2ae4ed9d74f0feb362eb9b40d5d5b7ca01b84f1eaf328510f69b7ed3fbb0a5"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "68ac543fa797c5b555eba02e0d5e594d691c983aba7e029dc097eaf9f3ae5e55"
start       = 0
end         = 0
[protocol.workers]
status_interval       = 10
milestone_sync_count  = 200

[rest_api]
bind_address          = "/ip4/0.0.0.0/tcp/14265"
feature_proof_of_work = true
public_routes         = [
    "/health",
    "/api/v1/info",
    "/api/v1/tips",
    "/api/v1/messages",
    "/api/v1/messages/:messageId",
    "/api/v1/messages/:messageId/metadata",
    "/api/v1/messages/:messageId/raw",
    "/api/v1/messages/:messageId/children",
    "/api/v1/outputs/:outputId",
    "/api/v1/addresses/:address",
    "/api/v1/addresses/ed25519/:address",
    "/api/v1/addresses/:address/outputs",
    "/api/v1/addresses/ed25519/:address/outputs",
    "/api/v1/receipts",
    "/api/v1/receipts/:milestoneIndex",
    "/api/v1/treasury",
    "/api/v1/transactions/:transactionId/included-message",
    "/api/v1/milestones/:milestoneIndex",
    "/api/v1/milestones/:milestoneIndex/utxo-changes",
]
allowed_ips = [
    "127.0.0.1",
    "::1"
]
white_flag_solidification_timeout = 2

[snapshot]
depth             = 50
interval_synced   = 50
interval_unsynced = 1000
full_path         = "./snapshots/comnet/full_snapshot.bin"
delta_path        = "./snapshots/comnet/delta_snapshot.bin"
[[snapshot.download_urls]]
full        = "https://cdn.tanglebay.com/snapshots/comnet/full_snapshot.bin"
delta       = "https://cdn.tanglebay.com/snapshots/comnet/delta_snapshot.bin"

[pruning]
enabled         = true
delay           = 60480
prune_receipts  = false

[storage]
path = "./storage/comnet/tangle"

[tangle]
below_max_depth = 15
num_partitions  = 16

[dashboard]
bind_address    = "/ip4/0.0.0.0/tcp/8081"
[dashboard.auth]
session_timeout = 86400
user            = "admin"
password_salt   = "0000000000000000000000000000000000000000000000000000000000000000"
password_hash   = "0000000000000000000000000000000000000000000000000000000000000000"

[tracing]
console_enabled = false
flamegraph_enabled = false
flamegraph_output_path = "./flamegraph"
