# Duplicate this file to config.toml to use it

alias      = "bee"
bech32_hrp = "iota"
network_id = "chrysalis-mainnet"

[logger]
[[logger.outputs]]
name              = "stdout"
level_filter      = "info"
target_filters    = []
target_exclusions = []
color_enabled     = true
[[logger.outputs]]
name              = "warn.log"
level_filter      = "warn"
target_filters    = []
target_exclusions = []

[network]
bind_address            = "/ip4/0.0.0.0/tcp/15600"
reconnect_interval_secs = 30
max_unknown_peers       = 4
max_discovered_peers    = 8

[network.peering]
#[[network.peering.peers]]
#address  = ""
#alias    = ""

[autopeering]
enabled                       = false
bind_address                  = "0.0.0.0:14626"
entry_nodes                   = [
    "/dns/entry-hornet-0.h.chrysalis-mainnet.iotaledger.net/udp/14626/autopeering/iotaPHdAn7eueBnXtikZMwhfPXaeGJGXDt4RBuLuGgb",
    "/dns/entry-hornet-1.h.chrysalis-mainnet.iotaledger.net/udp/14626/autopeering/iotaJJqMd5CQvv1A61coSQCYW9PNT1QKPs7xh2Qg5K2",
    "/dns/entry-0.mainnet.tanglebay.com/udp/14626/autopeering/iot4By1FD4pFLrGJ6AAe7YEeSu9RbW9xnPUmxMdQenC",
    "/dns/entry-1.mainnet.tanglebay.com/udp/14636/autopeering/CATsx21mFVvQQPXeDineGs9DDeKvoBBQdzcmR6ffCkVA",
]
entry_nodes_prefer_ipv6       = false
run_as_entry_node             = false
drop_neighbors_on_salt_update = false
peer_storage_path             = "./storage/mainnet/peers"

[protocol]
minimum_pow_score = 4000
[protocol.coordinator]
public_key_count  = 2
[[protocol.coordinator.public_key_ranges]]
public_key  = "a9b46fe743df783dedd00c954612428b34241f5913cf249d75bed3aafd65e4cd"
start       = 0
end         = 777600
[[protocol.coordinator.public_key_ranges]]
public_key  = "365fb85e7568b9b32f7359d6cbafa9814472ad0ecbad32d77beaf5dd9e84c6ba"
start       = 0
end         = 1555200
[[protocol.coordinator.public_key_ranges]]
public_key  = "ba6d07d1a1aea969e7e435f9f7d1b736ea9e0fcb8de400bf855dba7f2a57e947"
start       = 552960
end         = 2108160
[[protocol.coordinator.public_key_ranges]]
public_key  = "760d88e112c0fd210cf16a3dce3443ecf7e18c456c2fb9646cabb2e13e367569"
start       = 1333460
end         = 2888660
[[protocol.coordinator.public_key_ranges]]
public_key  = "7bac2209b576ea2235539358c7df8ca4d2f2fc35a663c760449e65eba9f8a6e7"
start       = 2108160
end         = 3359999
[[protocol.coordinator.public_key_ranges]]
public_key  = "edd9c639a719325e465346b84133bf94740b7d476dd87fc949c0e8df516f9954"
start       = 2888660
end         = 3359999
[[protocol.coordinator.public_key_ranges]]
public_key  = "47a5098c696e0fb53e6339edac574be4172cb4701a8210c2ae7469b536fd2c59"
start       = 3360000
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "ae4e03072b4869e87dd4cd59315291a034493a8c202b43b257f9c07bc86a2f3e"
start       = 3360000
end         = 0

[protocol.workers]
status_interval       = 10
milestone_sync_count  = 200

[rest_api]
bind_address          = "/ip4/0.0.0.0/tcp/14265"
jwt_salt              = "Bee"
public_routes         = [
      "/health",
      "/api/v1/info",
      "/api/v1/tips",
      "/api/v1/messages*",
      "/api/v1/transactions*",
      "/api/v1/milestones*",
      "/api/v1/outputs*",
      "/api/v1/addresses*",
      "/api/v1/treasury",
      "/api/v1/receipts*",
]
protected_routes       = [
      "/api/v1/*",
      "/api/plugins/*"
]
feature_proof_of_work = true
white_flag_solidification_timeout = 2

[snapshot]
depth             = 50
interval_synced   = 50
interval_unsynced = 1000
full_path   = "./snapshots/mainnet/full_snapshot.bin"
delta_path  = "./snapshots/mainnet/delta_snapshot.bin"
[[snapshot.download_urls]]
full        = "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-full_snapshot.bin"
delta       = "https://chrysalis-dbfiles.iota.org/snapshots/hornet/latest-delta_snapshot.bin"
[[snapshot.download_urls]]
full        = "https://cdn.tanglebay.com/snapshots/mainnet/full_snapshot.bin"
delta       = "https://cdn.tanglebay.com/snapshots/mainnet/delta_snapshot.bin"

[pruning]
[pruning.milestones]
enabled                = true
max_milestones_to_keep = 60480
[pruning.receipts]
enabled                = false
[pruning.size]
enabled                = true
target_size            = 30GB
threshold_percentage   = 10.0
cooldown_time          = 5m

[storage]
path = "./storage/mainnet/tangle"

[tangle]
below_max_depth = 15

[dashboard]
bind_address    = "/ip4/0.0.0.0/tcp/8081"
[dashboard.auth]
session_timeout = 86400
user            = "admin"
password_salt   = "0000000000000000000000000000000000000000000000000000000000000000"
password_hash   = "0000000000000000000000000000000000000000000000000000000000000000"

[tracing]
console_enabled = false
flamegraph_enabled = false
flamegraph_output_path = "./flamegraph"
