# Duplicate this file to config.toml to use it

alias      = "Bee stardust-testnet node"
bech32_hrp = "atoi"
network_id = "stardust-testnet-2"

[logger]
[[logger.outputs]]
name              = "stdout"
level_filter      = "info"
target_filters    = []
target_exclusions = []
color_enabled     = true
[[logger.outputs]]
name              = "warn.log"
level_filter      = "warn"
target_filters    = []
target_exclusions = []

[network]
bind_address            = "/ip4/0.0.0.0/tcp/15600"
reconnect_interval_secs = 30
max_unknown_peers       = 4
max_discovered_peers    = 8

[network.peering]
#[[network.peering.peers]]
#address  = ""
#alias    = ""

[autopeering]
enabled                       = false
bind_address                  = "0.0.0.0:14626"
entry_nodes                   = [
    "/dns/entry-hornet-0.h.stardust-testnet.iotaledger.net/udp/14626/autopeering/Bv8UUxy81fqpttowiFiBsNT6mnGMFoFNjk79iG1f9nEr",
    "/dns/entry-hornet-1.h.stardust-testnet.iotaledger.net/udp/14626/autopeering/CbYtFzRQtqeNQJQFYRZk1WewxfKCmqXCHZ16od1d23PX"
]
entry_nodes_prefer_ipv6       = false
run_as_entry_node             = false
drop_neighbors_on_salt_update = false
peer_storage_path             = "./storage/shimmer/testnet/peers"

[protocol]
minimum_pow_score = 1000
[protocol.coordinator]
public_key_count  = 3
[[protocol.coordinator.public_key_ranges]]
public_key  = "d9922819a39e94ddf3907f4b9c8df93f39f026244fcb609205b9a879022599f2"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "d85e5b1590d898d1e0cdebb2e3b5337c8b76270142663d78811683ba47c17c98"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "f9d9656a60049083eef61487632187b351294c1fa23d118060d813db6d03e8b6"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "3df80964cc83921e08c1fa0a4f5fc05810a634da45461b2b315fcbfd62f7cab7"
start       = 0
end         = 0
[[protocol.coordinator.public_key_ranges]]
public_key  = "8e222ae7e2adcfb87a2984a19aad52b1979ed1472c3cb17239a73ef1d344c35a"
start       = 0
end         = 0

[protocol.workers]
status_interval       = 10
milestone_sync_count  = 200

[rest_api]
bind_address          = "/ip4/0.0.0.0/tcp/14265"
feature_proof_of_work = true
public_routes         = [
    "/health",
    "/api/v2/info",
    "/api/v2/tips",
    "/api/v2/messages",
    "/api/v2/messages/:messageId",
    "/api/v2/messages/:messageId/metadata",
    "/api/v2/messages/:messageId/raw",
    "/api/v2/messages/:messageId/children",
    "/api/v2/outputs/:outputId",
    "/api/v2/addresses/:address",
    "/api/v2/addresses/ed25519/:address",
    "/api/v2/addresses/:address/outputs",
    "/api/v2/addresses/ed25519/:address/outputs",
    "/api/v2/receipts",
    "/api/v2/receipts/:milestoneIndex",
    "/api/v2/treasury",
    "/api/v2/transactions/:transactionId/included-message",
    "/api/v2/milestones/:milestoneIndex",
    "/api/v2/milestones/:milestoneIndex/utxo-changes",
]
allowed_ips = [
    "127.0.0.1",
    "::1"
]
white_flag_solidification_timeout = 2

[snapshot]
depth             = 50
interval_synced   = 50
interval_unsynced = 1000
full_path   = "./snapshots/shimmer/testnet/full_snapshot.bin"
delta_path  = "./snapshots/shimmer/testnet/delta_snapshot.bin"
[[snapshot.download_urls]]
full        = "https://files.stardust-testnet.iotaledger.net/snapshots/latest-full_snapshot.bin"
delta       = "https://files.stardust-testnet.iotaledger.net/snapshots/latest-delta_snapshot.bin"

[pruning]
enabled         = true
delay           = 60480
prune_receipts  = false

[storage]
path = "./storage/shimmer/testnet/tangle"

[tangle]
below_max_depth = 15
num_partitions  = 16

[mqtt]
address = "tcp://localhost:1883"

[dashboard]
bind_address    = "/ip4/0.0.0.0/tcp/8081"
[dashboard.auth]
session_timeout = 86400
user            = "admin"
password_salt   = "0000000000000000000000000000000000000000000000000000000000000000"
password_hash   = "0000000000000000000000000000000000000000000000000000000000000000"
