name: Docs

on:
  push:
    branches:
      - dev
      - stable
      - coordicide
  pull_request:
    branches:
      - dev
      - stable
      - coordicide

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ubuntu-latest-stable-cargo-registry-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ubuntu-latest-stable-cargo-index-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo target
      uses: actions/cache@v2
      with:
        path: target
        key: ubuntu-latest-stable-cargo-target-${{ hashFiles('**/Cargo.toml') }}

    - uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-deps
