name: Licenses

on:
  push:
    branches:
      - dev
      - stable
      - coordicide
  pull_request:
    branches:
      - dev
      - stable
      - coordicide

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
    - uses: actions-rs/cargo@v1
      name: Install cargo-about
      with:
        command: install
        args: cargo-about
    - uses: actions-rs/cargo@v1
      name: Initialize template
      with:
        command: about
        args: cargo about --workspace --all-features init
    - uses: actions-rs/cargo@v1
      name: Check licenses
      with:
        command: about
        args: cargo about --workspace --all-features generate about.hbs
