name: Missing files

on:
  push:
    branches:
      - dev
      - stable
      - coordicide
  pull_request:
    branches:
      - dev
      - stable
      - coordicide

jobs:
  missing_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run missing files check
        run: bash .github/workflows/scripts/missing_files.sh
