[package]
name = "bee-crypto"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Cryptographic primitives of the IOTA protocol"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "crypto"]
homepage = "https://www.iota.org"

[dependencies]
bee-ternary = "0.3.1-alpha"

byteorder = "1.3.4"
lazy_static = "1.4.0"
thiserror = "1.0.20"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
rand = "0.7.3"
